version: '2'
services:
  smt_db:
    container_name: smt_db
    image: mariadb:10.10
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - smt_backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    
  smt_wordpress:
    container_name: smt_wordpress
    depends_on:
      - smt_db
      - smt_redis
    image: wordpress:php8.1
    volumes:
      - ./data:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: unless-stopped
    networks:
      - smt_backend
      - proxy
    environment:
      WORDPRESS_DB_HOST: smt_db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'smt_redis' );
        define( 'WP_REDIS_PORT', 6379 );
    labels:
      - traefik.enable=true
      - traefik.http.routers.smt.entrypoints=http
      - traefik.http.routers.smt.rule=Host("mycotra.org", "www.mycotra.org", "mycotra.ch", "www.mycotra.ch")
      - traefik.http.middlewares.smt-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.smt.middlewares=smt-https-redirect, smt-redirect
      - traefik.http.middlewares.smt-redirect.redirectregex.regex="^https://mycotra.ch"
      - traefik.http.middlewares.smt-redirect.redirectregex.replacement="https://mycotra.org"
      - traefik.http.routers.smt-secure.entrypoints=https
      - traefik.http.routers.smt-secure.rule=Host("mycotra.org", "www.mycotra.org", "mycotra.ch", "www.mycotra.ch")
      - traefik.http.routers.smt-secure.tls=true
      - traefik.http.routers.smt-secure.tls.certresolver=http
      - traefik.docker.network=proxy
      
  smt_redis:
      container_name: smt_redis
      image: redis:7
      expose:
          - 6379
      restart: unless-stopped
      networks:
           - smt_backend

networks:
  smt_backend:
  proxy:
    external: true
